sudo: required
dist: trusty

os:
  - linux
  - osx

language: java
jdk: openjdk8

install: unset _JAVA_OPTIONS
script: ./gradlew build

before_cache:
  - rm -f $HOME/.gradle/caches/{modules-2,transforms-1}/*.lock
  - rm -rf $HOME/.gradle/caches/*/{file-changes,fileHashes,plugin-resolution,scripts,scripts-remapped,gradle-script-kotlin}/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false
